### ISSUE TITLE
A页面跳转到使用princhzoom的页面，点击返回按钮，地址返回页面没有响应出现白屏

### ISSUE THREAD

**Issue by zhuaimaodoudou** [manuelstofer/pinchzoom#107]
A页面路由跳转到使用princhzoom的页面，点击返回按钮，想返回到上一页，结果URL地址返回但是页面没有响应出现白屏

**Comment by sandstrom** [comment]
Sorry, but I don't understand any of this. My native language isn't english either, but that's what most people use to communicate globally so that's what we'll be using here. You'll have to rephrase this in english if you want to communicate around this open-source project.

***

Is this an issue with the code itself, or a general question? For general questions [Stackoverflow](https://stackoverflow.com/) is better than Github.

I'm closing this now, but I'm willing to reopen if there is an actual code issue. If so, steps to reproduce (and ideally a failing test-case) is a good start.
