### ISSUE TITLE
Mouse support with mouse scroll

### ISSUE THREAD

**Issue by benjaminmcdonald** [manuelstofer/pinchzoom#108]
Would it be realistic to modify this library to add scroll and zoom with mouse controls?

**Comment by sandstrom** [comment]
I'm not sure that would be a good fit for this library. 

What we could support, mouse-wise, would be double-clicking to trigger zoom in, just like double-tap works today.

**Comment by sandstrom** [comment]
Thanks for thinking about how this project can be improved! Since this code is open-source, without anyone getting paid to work on it, it's difficult to satisfy all the wishes that people may have. I hope you understand! 🌻 

I'm going to close this issue. But if you want to help out improving this project I'm happy to discuss and give feedback on a proposed change.
