### ISSUE TITLE
Double Tap and zoom event

### ISSUE THREAD

**Issue by Funnybanny** [manuelstofer/pinchzoom#130]
According to the very limited documentation "onZoomStart", "onZoomEnd", "onZoomUpdate" callbacks should run on zoom. On double tapping the picture only "onZoomUpdate" is called. BreakPoints on "onZoomEnd" and "onZoomStart" never get hit.

```
var pz = new PinchZoom.default(i[0], {
        maxZoom: ocrScaleMax,
        onZoomUpdate: function (object, event) {
            ocrPinchZoomEvent(object);
        },
        onZoomEnd: function (object, event) {
            var tmp = 0;
        },
        onZoomStart: function (object, event) {
            var tmp = 0;
        }
```

**Comment by sandstrom** [comment]
Thanks for thinking about how this project can be improved! Since this code is open-source, without anyone getting paid to work on it, it's difficult to satisfy all the wishes that people may have. I hope you understand! 🌻 

So if you want something, a good first step is to explain in detail what you think should be changed. If others agree that it's a good idea, the next step would be for you to open a PR with the necessary code changes.

I'm going to close this issue. But if you want to help out improving this project I'm happy to discuss and give feedback on a proposed change.
