### ISSUE TITLE
After zoom and on initial loading img displacement

### ISSUE THREAD

**Issue by Funnybanny** [manuelstofer/pinchzoom#131]
On initial loading and on zoom the image is positioned with `transform: translate(x px, y px)` to the middle of the page. How do I turn this off? I dont want to touch the library code, so I am hoping there is some kind of hidden solution.

**Comment by sandstrom** [comment]
I don't know if there is a way to turn it off, unfortunately.

Since this code is open-source, without anyone getting paid to work on it, it's difficult to satisfy all the wishes that people may have. I hope you understand! 🌻 

So if you want something, a good first step is to explain in detail what you think should be changed. If others agree that it's a good idea, the next step would be for you to open a PR with the necessary code changes.

I'm going to close this issue. But if you want to help out improving this project I'm happy to discuss and give feedback on a proposed change.

**Comment by sandstrom** [comment]
Also, is this issue relevant? https://github.com/manuelstofer/pinchzoom/issues/93
