### ISSUE TITLE
Unbind events functionality

### ISSUE THREAD

**Issue by antoniobrandao** [manuelstofer/pinchzoom#24]
Is there is way to unbind elements after they are initialised? To remove listeners / avoid memory leaks / etc when we remove the elements from the DOM to show new elements.

I'm attempting to use pinchzoom.js in a touch-gallery, and I will often remove collections of initialised images to add new ones. Are the events automatically removed when I remove the elements from the DOM or do we need an "unbind" functionality?

**Comment by sandstrom** [comment]
When elements are removed from the DOM their listeners will be cleared too.

This SO-question describes it in detail:
https://stackoverflow.com/questions/12528049/if-a-dom-element-is-removed-are-its-listeners-also-removed-from-memory

As described, there are also issues where this won't happen. Are there any issues with the code that you've spotted?

Otherwise, afaik the listeners will be torn down when you remove the element.

**Comment by sandstrom** [comment]
Closing, since there is no answer I assume this issue is solved. Let me know if that isn't the case and we may reopen it.

**Comment by northkode** [comment]
@sandstrom  you are making a big assumption that the developer has cleaned up all references to the element in question out side of your code.

Therefore, if I cant explicitly call a destroy method on your functionality it will contribute to a memory leak long term. It is best to allow the developer to call a clean up method and not rely on the browsers garbage collection to "hopefully" do it.

**Comment by sandstrom** [comment]
I answered the question:

> Are the events automatically removed when I remove the elements from the DOM or do we need an "unbind" functionality?

My answer may be incorrect, but I don't think so. 

Let me know if you disagree and please include links/references explaining why/how my assumption is wrong.

**Comment by northkode** [comment]
I'm not sure if you read my message.. but I did explain why I think you might be wrong. 

Event listeners only clean themselves up if ALL memory pointers in the application don't have a reference to the item that is bound to this component.. and so you are assuming that the programmer cleaned up all other reference pointers instead of just providing a proper destroy handler to remove the pointers you just created in your code.

By saying, "oh the browser will just clean it up during garbage collection," that is a very dangerous assumption because if it doesn't - which I've seen all the time due to reference pointers getting lost - your library  is now also contributing to the memory leak problem.  

But at the end of the day, your library your call.

**Comment by sandstrom** [comment]
@northkode Alright, makes sense!

Happy to consider a PR if you want to work on this.

Actually it's not my library. The original maintainer/author doesn't have time to work on it so I'm volunteering  some of my free time to keep the library alive…
