### ISSUE TITLE
Android double tap not working very well?

### ISSUE THREAD

**Issue by RookieDouby** [manuelstofer/pinchzoom#46]
I tried the demo in andriod device, when I double tap the image, zoom in works well.But when I double tap again, image won't zoom out to original zoomFactor.

**Comment by sandstrom** [comment]
@RookieDouby Is there a difference between iOS and Android? Between different versions of Android?

**Comment by RookieDouby** [comment]
@sandstrom iOS works well, doubletap zoom in and again zoom out.But when I use Galaxy S7(6.0.1), when zoomFactor > 1, doubletap won't reset to original zoom. I will try other Android devices.

**Comment by sandstrom** [comment]
@RookieDouby Awesome, let me know what you find. We need more precision around the version.

When you say "iOS works", which version of iOS are you talking about? And ditto for Android

**Comment by paladinzyh** [comment]
I met the same problem. IOS 10.3.3 works well, but Android MIUI 8.5 can't zoom out when I double tap again.  and more serious problem is: I can't zoom with two fingers. The picture is not zooming when I move my fingers on the screen, but after I raise my fingers, the picture is zoomed.

**Comment by sandstrom** [comment]
What code are you running? Can you provide a breaking test-case? Does the test-case also work under some circumstances?

**Comment by Andydabing** [comment]
I met the same problem，Android can't zoom out when I double tap again.

**Comment by sandstrom** [comment]
@Andydabing You are right! Would you like to take a look at it? A PR with a fix for this issue would be much appreciated!

**Comment by micgro42** [comment]
We are adjusting this library in some aspects and fixed this bug in https://github.com/cosmocode/ms-pinchzoom/commit/579348cbc13d0577bc944741a93101faa2e288de

**Comment by sandstrom** [comment]
@micgro42 Awesome! We'll happily introduce your fix into the repo. 🏅 

I also noted that you've made quite a few other changes. Most (all?) of them look really good, so I'm also happy to introduce them if you are interested?

I may have some minor comments about a few of them though, some notes below:

- Scroll-detect on Android (https://github.com/cosmocode/ms-pinchzoom/commit/e64fdc2c57e6b750957106dbee8d849b3fadbaf7) => Happy to include this one as it is
- Use parent dimensions (https://github.com/cosmocode/ms-pinchzoom/commit/e15c62c5718720f2cb8ecf7a8fa629b6160bdb0c) => Is there a reason to place this under a flag/option, to avoid breaking backwards compatibility. Or would you say this is a non-breaking change?
- Center initially (https://github.com/cosmocode/ms-pinchzoom/commit/86ff37813a7011e73b43ac8852e51da498a059d2) => Looks good overall, some minor comments, for example I'd use `zoomFactor` instead of `zoomFaktor`.
- Dragging beyond an elements edge (https://github.com/cosmocode/ms-pinchzoom/commit/1feb43dc6a6a06d7cac14a3f96a435ecd86b7e45) => Seems like a good thing, but perhaps `verticalPadding` or `verticalOverflow` would be better option-names?

(regarding breaking changes, I'm also fine with doing them, and in that case we'll just release the changes as 3.x)

**Comment by micgro42** [comment]
On second thought, some of these changes are quite intertwined and disentangling them is a non-trivial task.

Are there any aspects you would prefer not to merge into your master branch? If not, then I would simply open a pull request for the entire cosmocode branch.

Note that we made a few more fixes in the last days, but they should not be poblematic.

Since the library now centers images automatically, it might be good to consider this a breaking change, even though the syntax is still the same.

**Comment by sandstrom** [comment]
Sounds good! You've made some impressive improvements here, I'm sure they would be helpful to others too! 🏆 

We can use a single pull-request. But would be great if you could still break the changes into separate commits.

One way may be to (1) take the entire diff between this branch and yours (~15 or so commits), (2) mash them together into a single commit and then (3) break this apart again, into new atomic commits. (4) These new commits can then be used for a PR into here.

That way, some of your subsequent changes would not be separate commits. For example, these two commits (https://github.com/cosmocode/ms-pinchzoom/commit/1feb43dc6a6a06d7cac14a3f96a435ecd86b7e45 and https://github.com/cosmocode/ms-pinchzoom/commit/ebe16c6934665d9932b3806a7cdfb529d0a91a3b) would only be one commit in the PR.

***

I'm open to changing the build-tools, but would prefer to wait with that. So we can keep webpack out of the PR to begin with.

I think we can include these things in the PR:

- [ ] feat: always show entire element on initialization (+ feat: always set container dimensions based on parent) [make this one commit]
- [ ] fix: correctly detect scroll on Android (+ fix: let scroll detection work on both android and iOS) [make this one commit]
- [ ] feat: scale to fit and center initially
- [ ] feat: add options to allow dragging beyond the elements edge ( + ebe16c6934665d9932b3806a7cdfb529d0a91a3b + https://github.com/cosmocode/ms-pinchzoom/commit/501da731319acd37ab2011be1d4ba1d8e76a9bf8)
- [ ] fix: don't treat doubletap as touchmove

***

I would like to understand these commits a bit better first (we can wait with them):
- [ ] feat: scale to fit and center initially
- [ ] feat: recalculate initial offset on resize
- [ ] fix: ensure initialization runs even without load event => I left [a comment](https://github.com/cosmocode/ms-pinchzoom/commit/18f837c3b1e87db30a1b196044d6cfdf4bc7b66e#commitcomment-26960833) on this commit, I think we can improve this, let me know what you think!

**Comment by sandstrom** [comment]
@micgro42 🏅 wrote a fix for this issue, so I'm closing it
