### ISSUE TITLE
Cool stuff...

### ISSUE THREAD

**Issue by neilyoung** [manuelstofer/pinchzoom#71]
...thanks for sharing

**Comment by neilyoung** [comment]
Maybe the only little issue: Somewhat applies an approx. 20px shift to right on first draw. Can be seen with a non-white background.

**Comment by neilyoung** [comment]
Yepp. If I comment this:

```
            /**
             * Compute the initial offset
             *
             * the element should be centered in the container upon initialization
             */
            computeInitialOffset: function computeInitialOffset() {
//                this.initialOffset = {
//                    x: -Math.abs(this.el.offsetWidth * this.getInitialZoomFactor() - this.container.offsetWidth) / 2,
//                    y: -Math.abs(this.el.offsetHeight * this.getInitialZoomFactor() - this.container.offsetHeight) / 2
//                };
            },


```

everything is properly aligned.

**Comment by sandstrom** [comment]
@neilyoung Thanks for the praise! 🙏 

Regarding the issue (20px shift on first draw), if you'd like to submit a patch to fix the bug I'm happy to review it.

Since this is a project maintained by volunteers we don't have the manpower to investigate bugs ourselves (we need help from others in the community, such as you). So I'm going to close this issue.

But again, happy to review a PR that explains and fixes the bug you mention.
