### ISSUE TITLE
Doubletap event happens but UX is not reflected

### ISSUE THREAD

**Issue by leomoty** [manuelstofer/pinchzoom#78]
Hello, I am trying to integrate this library with Swipejs.

I am not sure whether I got into a bug or I am not supposed to populate the contents of the pinch-zoom after `pinchzoom` is loaded. 

This is my jsfiddle demo: https://fiddle.jshell.net/leomoty/swt4qvbe/30/show/,  which I tried with both chrome device emulator and a proper device. It might require some tries to reproduce.

It is not exactly what I am doing but it is enough to reproduce the behavior.

## What did I expect

When you doubletap shortly after page is loaded, the current in range image would get zoomed in.

## What happened instead

If you check console, you'll notice that `doubletap` event is indeed fired, followed by some `zoomupdate` ones. But visually nothing has happened.

## Side effect

PZ will now behave as if it were zoomed in and thus you can't swipe until you doubletap again.

**Comment by zyniq82** [comment]
@leomoty, your fiddle isn't working for me. First of all, the URL doesn't work, so I had to change it to https://jsfiddle.net/leomoty/swt4qvbe/30/ (not sure if it's the same fiddle). Secondly, no images seem to render.

I am writing to let you know I am also using Swipe together with PinchZoom, which works. PinchZoom used to work out-of-the-box with Swipe, but after some changes in PinchZoom it didn't anymore. As a result I've added the `draggableUnzoomed` option to PinchZoom, to allow it to pass on swipe events to Swipe. Have you tried setting `draggableUnzoomed` to false? It should make things swipable. 

Another point is Swipe itself, which isn't maintained anymore. I'd recommend the maintained fork at https://github.com/lyfeyaj/swipe (I'm using version `2.2.11`).

Lastly, I might be misunderstanding, but it appears to me you can't swipe while the image is zoomed in. This is the expected behaviour, since otherwise one wouldn't be able to pan the image left/right when it is zoomed in.

Best of luck! :four_leaf_clover:

**Comment by leomoty** [comment]
Hello @zyniq82, first of all thanks for the late response, I even forgot I had opened this.

Yes, my demo did rot quite significantly since then. I was able to solve my issue after all. We are dynamically appending content and it had some issues on startup, I just reworked so the pinchzoom layer is only created when needed. Also ended using `draggableUnzoomed: false` as you suggested.
