### ISSUE TITLE
Can someon enable scrollwheel zoom on this to finally make one thing that works on Mobile and Desktop?

### ISSUE THREAD

**Issue by bjornmuh** [manuelstofer/pinchzoom#97]

**Comment by sandstrom** [comment]
Thanks for thinking about how this project can be improved! Since this code is open-source, without anyone getting paid to work on it, it's difficult to satisfy all the wishes that people may have. I hope you understand! 🌻 

So if you want something, a good first step is to explain in detail what you think should be changed. If others agree that it's a good idea, the next step would be for you to open a PR with the necessary code changes.

I'm going to close this issue. But if you want to help out improving this project I'm happy to discuss and give feedback on a proposed change.
